### ISSUE TITLE
Add `og:locale` option

### ISSUE THREAD

**Issue by christopherpickering** [tannerdolby/eleventy-plugin-metagen#10]
Hi! Thanks for the tool. Can we add `og:locale` option?

```html
<meta property="og:locale" content="en_US"/>
```

**Comment by tannerdolby** [comment]
Hi! You're welcome, and sure thing. That sounds like a good option to have. Thanks for the suggestion.

I should have the `<meta property="og:locale">` tag added to the plugin later tonight or over the weekend.

**Comment by tannerdolby** [comment]
Support has been added in [10c7a0a](https://github.com/tannerdolby/eleventy-plugin-metagen/commit/10c7a0ae6568e7652e4bec2c787a8c670a0742d8) to define a `og:locale` meta tag 🚀  

The default is `en_US` and can be altered by using the `locale` parameter. Thank you again for bringing this up @christopherpickering!

**Comment by tannerdolby** [comment]
Also, there is now a documentation site for this plugin!

https://metagendocs.netlify.app

**Comment by christopherpickering** [comment]
Thanks!

**Comment by tannerdolby** [comment]
Your welcome!
