### ISSUE TITLE
Add support for different og:type

### ISSUE THREAD

**Issue by teamcrisis** [tannerdolby/eleventy-plugin-metagen#14]
https://github.com/tannerdolby/eleventy-plugin-metagen/blob/master/.eleventy.js#L13

Shouldn't this be user defined? For example `website`, `product` or `article`?

**Comment by tannerdolby** [comment]
Hey 👋  @teamcrisis 

Yeah I think that is a really good option to have! Thank you for bringing this to light.

**Comment by tannerdolby** [comment]
I added support to make `og:type` a user-defined field in [34c6e00](https://github.com/tannerdolby/eleventy-plugin-metagen/commit/55b1a86c56d77428c8e140f1669c5a6e34de83b5). I will be publishing v1.5+ to npm shortly.

Feel free to update the package to v1.5+ to take advantage of the `type` parameter when using `metagen` in a template! Let me know if there is anything else you would like to see for this plugin and I'm happy to take it into consideration. 

`npm install eleventy-plugin-metagen@latest` works to grab the latest version.

**Comment by teamcrisis** [comment]
Thank you!

**Comment by tannerdolby** [comment]
You're welcome! 🎉
