### ISSUE TITLE
Variables are not rendering properly for og:url and canonical tags

### ISSUE THREAD

**Issue by sergehf** [tannerdolby/eleventy-plugin-metagen#16]
Hello,

We're using a variable to generate permalinks for paginated content, which is also being used to create the og:url and canonical tags. The permalink works fine and the pages are created as expected, but when checking the source code, the variables are not rendered as a slug but as the actual variable.

So for example, our permalink is: `permalink: /company/careers/{{ pagination.items[0].id }}/` which gets rendered to something like /company/careers/0234asdf234/ 

But what get's rendered in the source for the og:url and the canonical is: `/company/careers/{{ pagination.items[0].id }}/`

Any ideas on what the issue might be?

**Comment by tannerdolby** [comment]
👋  @sergehf Thank you for raising your issue. At first glance, I have a feeling it has to do with one or two things:

1. the order of operations when eleventy builds the site, meaning the metagen plugin didn't have access to the interpolated data for `{{ pagination.items[0].id }}` from frontmatter or another data source so it just rendered it as the plain text with the doubly curly braces. 

If you include a little bit more of the structure for your issue, i.e. the .njk/.liquid/.md file that your defining the `permalink` in for your paginated collection, and then also the file/example of how your trying to use `{{ pagination.items[0].id }}` with `metagen` that will help me to figure out how to diagnose this. 

i.e. are you passing it inline like:
```
---
pagination:
    data: items
    size: 1
    alias: item
permalink: "/company/careers/{{ pagination.items[0].id }}/"
---
{% metagen 
    ....
    url=pagination.items[0].id or item.id
%}
```
or from another data source (frontmatter, global data)

```
---
url: {{ pagination.items[0].id }} <-- this might not render as {{ var }} cant reliably render template data in frontmatter
---

{% metagen 
    ....
    url=url
%}
```

2. Possibly your using brackets when using the template variable with metagen when defining fields inline like:

```html
{% metagen 
    ....
    url={{ pagination.items[0].id }}
%}
```

the plugin expects when your [using template data](https://github.com/tannerdolby/eleventy-plugin-metagen#use-your-template-data) to not enclosed variables in doubly curly braces and just leave them as is like:

```
---
pagination:
    data: items
    size: 1
    alias: item
permalink: "/company/careers/{{ pagination.items[0].id }}/"
bar: hello
---
{% metagen 
    ....
    url=item.id,
    foo=bar
%}

**Comment by reatlat** [comment]
@tannerdolby TY for quick response,
I'm @sergehf teammate :)

we call `metagen` in partial file, which is part of layout(s)...

Solved by little tweak

```
{% metagen 
    ....
    url=( '/company/careers/' + item.id + '/' or  permalink )
%}
```

**Comment by tannerdolby** [comment]
👋 @reatlat NP! Nice to meet you :)

Ok great, I'm glad to hear you were able to get things figured out. Going to close this issue now, feel free to let me know if you have any more questions or concerns.
