### ISSUE TITLE
Bump Eleventy Version

### ISSUE THREAD

**Issue by miklb** [tannerdolby/eleventy-plugin-metagen#25]
Currently the version for Eleventy is `^1.0.1` which is throwing a vulnerability warning for `liquidjs`.

I haven't experienced any issues with the plugin and the current stable version (2.0.1)  of Eleventy.

**Comment by tannerdolby** [comment]
👋 @miklb Thank you for bringing this up. I will upgrade Eleventy to 2.0.1 and get a new version of this plugin published soon.

**Comment by tannerdolby** [comment]
Apologies for the delay. Fixed in versions v1.8.2+
