### ISSUE TITLE
OpenGraph image meta is incorrect

### ISSUE THREAD

**Issue by JbIPS** [tannerdolby/eleventy-plugin-metagen#3]
Hi,

I just tried this useful plugin but I noticed something's wrong: the `og:img` (and `:alt`) does not exist in the [spec](https://ogp.me/#structured) and should be replaced by `og:image`.

I can do a PR, just giving you a heads up first :wink:

**Comment by tannerdolby** [comment]
Hello @JbIPS !

Good catch. Yes, feel free to submit a PR and replace the `og:img` and `:alt` with `og:image`.

Thanks for the heads up.
