### ISSUE TITLE
Update version in package.json

### ISSUE THREAD

**Issue by tannerdolby** [tannerdolby/eleventy-plugin-metagen#6]
The plugin has seen some needed improvements in the last week thanks to the keen eye of @JbIPS !

Therefore, I think it's time to increment the version from `1.0.3` to `1.0.4` or potentially `1.1.4` as discovering the plugin *does* support template variables is more than a "patch improvement" and very well could warrant a MINOR version increment. Also, the fix with `og:img` being replaced with `og:image` to satisfy the spec, warrants a PATCH version increment. 

After I do some local testing of the changes merged into `master` within the last week, I will update the package `version` to reflect the MINOR and PATCH version increments necessary.

**Comment by JbIPS** [comment]
I agree with you on the MINOR update. But if you're following semver, next version should be `1.1.0` since minor bump reset the patches.

P.S.: I don't know if you've ever use this but I encourage you to use [`npm version minor`](https://docs.npmjs.com/cli/v7/commands/npm-version) to do so, since it will take care of a lot of things for you :wink:

**Comment by tannerdolby** [comment]
Ah, yes you are correct that the minor bump will reset the patches. I will close this when I update things later today.

Thank you for the reminder and for mentioning `npm version minor` 😃

**Comment by tannerdolby** [comment]
@JbIPS I'm actually so thrilled to see the template variables work in the shortcode. I'm updating my sites that use the plugins now and it's such a good feeling. Thank you again for bringing this to my attention!

**Comment by tannerdolby** [comment]
Closed via [`65dc71f`](https://github.com/tannerdolby/eleventy-plugin-metagen/commit/65dc71faa92afd8713d62fd8f6e4b49fe1e6990d)
