### ISSUE TITLE
Thoughts on adding a meta tag for "keywords"

### ISSUE THREAD

**Issue by tannerdolby** [tannerdolby/eleventy-plugin-metagen#8]
Anyone want to weigh in on potentially adding a meta tag for keywords to the plugin like

```
<meta name="keywords" content="eleventy, foo, bar">
```

I'm currently using the `eleventy-plugin-metagen` plugin to generate all other social share meta tags but the "keywords" tag is the only one I'm manually entering outside of the generated meta tags from the plugin. It would require the docs to be updated and a few line changes in `.eleventy.js`

**Comment by tannerdolby** [comment]
@JbIPS thoughts on this?

**Comment by JbIPS** [comment]
I'm not sure if this meta tag is still useful but as long as it's optional I'd say go for it!

**Comment by tannerdolby** [comment]
> Today, it’s pretty clear the meta keyword tag is dead in terms of SEO value. [Meta keywords are dead](https://yoast.com/meta-keywords/)

You are correct. the `<meta name="keywords" ..>` tag is now considered irrelevant and "is dead in terms of SEO". Therefore, I don't see any reason to add it to the plugins functionality. Thank you for the feedback!
