### ISSUE TITLE
Twitter summary_large_image

### ISSUE THREAD

**Issue by tpiros** [tannerdolby/eleventy-plugin-metagen#9]
How would one configure your plugin to generate a large image preview card for Twitter via the `summary_large_image`?

**Comment by tannerdolby** [comment]
@tpiros Thank you for bringing this to my attention. Currently, the plugin doesn't generate a `summary_large_image` to provide a large image preview for the Twitter Summary card.

I will add support for `summary_large_image` by the end of day.

**Comment by tpiros** [comment]
Sounds awesome. I did change it around locally, doesn't seem to be a massive change. Appreciate the fast response!

**Comment by tannerdolby** [comment]
No problem! Yeah your right, not a massive change. I'm planning on adding another parameter to the shortcode, `twitter_card_type` that will take a string parameter to define the `content` for `<meta name="twitter:card">`. The default value will be `content="summary"` if the `twitter_card_type` param isn't defined or is an empty string. I'll ping you in the morning when it's updated.

Usage:
```html
<head>
  <!-- creates <meta name="twitter:card content="summary_large_image" -->
  {% metagen 
      title="Some title",
      ...
      twitter_card_type="summary_large_image",
      ...
  %}
</head>
```

Without the param `twitter_card_type` defined or if its an empty string:

```html
<head>
  <!-- creates <meta name="twitter:card content="summary" -->
  {% metagen 
      title="Some title",
      ... 
      ...
  %}
</head>
```

**Comment by tannerdolby** [comment]
@tpiros Fixed with commit [3b8a551](https://github.com/tannerdolby/eleventy-plugin-metagen/commit/3b8a55128115ccfba5719977803d6eda4e48cdca) 🎉 🚀

After running `npm update` on my personal website code, the plugin works as expected. Providing the large summary image in Twitter card if `twitter_card_type="summary_large_image"` was used.

<img width="998" alt="Screen Shot 2021-04-21 at 12 40 53 AM" src="https://user-images.githubusercontent.com/48612525/115515872-6585c300-a23a-11eb-94ed-3f765afb8d1d.png">

**Comment by tannerdolby** [comment]
@tpiros Fixed with [commit 3b8a551](https://github.com/tannerdolby/eleventy-plugin-metagen/commit/3b8a55128115ccfba5719977803d6eda4e48cdca)

**Comment by tpiros** [comment]
@tannerdolby awesome job! Checked and works as expected! And it works amazingly well with my auto social share card generator! :-)

<img width="1078" alt="Screenshot 2021-04-21 at 14 19 07" src="https://user-images.githubusercontent.com/2042718/115552388-91da2780-a2ac-11eb-90cf-7f795d55bb5b.png">

**Comment by tannerdolby** [comment]
@tpiros thanks! I'm glad everything is working as expected. Your social share card created by the generator looks great! Feel free to let me know if you encounter any bugs.
